<div
    class="
        bg-gradient-to-b
        from-blue-500
        to-blue-800
        md:relative md:h-screen
        z-10
        lg:w-64
        md:w-48
    "
    >
    <div
        class="
        lg:w-full
        md:content-start
        "
    >
        <ul
        class="
            flex flex-row
            md:flex-col
            md:py-3
            text-center
            w-auto
        "
        >
        <li class="mx-auto my-5 cursor-pointer">
            <a data-aos="fade up" data-aos-duration="500" data-aos-delay="100" href="#">
                <img src="{{ asset('image/logo.png') }}" alt="Logo" width="70" />
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl
                block
                font-bold
                md:inline-block
                "
                >Dashboard</span
            >
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl

                block
                font-bold
                md:inline-block
                "
                >Class</span
            >
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl
                block
                font-bold
                md:inline-block
                "
                >Subject</span
            >
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl

                block
                font-bold
                md:inline-block
                "
                >Theory</span
            >
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl

                block
                font-bold
                md:inline-block
                "
                >Video</span
            >
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl

                block
                font-bold
                md:inline-block
                "
                >Comment</span
            >
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl

                block
                font-bold
                md:inline-block
                "
                >Profile</span
            >
            </a>
        </li>
        <li class="flex-1">
            <a
            href="#"
            class="
                block
                md:py-3
                align-middle
                text-white
                hover:bg-blue-800
                hover:text-yellow-400
                transition
                duration-150
                "
                >
                <span
                class="
                pb-1
                md:pb-0
                text-xl

                block
                font-bold
                md:inline-block
                "
                >Logout</span
            >
            </a>
        </li>
        </ul>
    </div>
    </div>
